---
title: "Downloading and analyzing ruffed grouse drumming data from WildTrax"
author: "Andy Crosby"
site: bookdown::bookdown_site
output: 
  md_document:
    variant: gfm
    toc: TRUE
    toc_depth: 2
    number_sections: TRUE
#bibliography: library.bib
#citation-style: ../../MendeleyBib/CitationStyles/nature.csl
#citation-style: https://www.zotero.org/styles/elsevier-harvard
link-citations: true
github-repo: https://github.com/baynelab-research/rugr-population-estimate
description: "This is document walks through the analyses I performed for this research."
---

# Overview

```{r GlobalOptions, echo=FALSE}
options(bookdown.render.file_scope = FALSE, knitr.duplicate.label = "allow") 
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

```{r setup, include=FALSE, cache=FALSE}
#Set root directory to R project root
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

```{r echo=FALSE, out.width = '100%'}
library(kableExtra)
library(knitr)
```



# Example Project

**Project description**
The Objective of this project is to use estimate Ruffed Grouse (*Bonasa umbellus*) population size in Alberta using data collected with autonomous recording units (ARUs). 




```{r child = '1_scripts/01_create-database.Rmd'}
```



# References


<div id="refs"></div>



